# Generated by Django 3.1.7 on 2021-03-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDegerler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kk_sayfa_ilk', models.SmallIntegerField(verbose_name='Başlangıç')),
                ('kk_sayfa_son', models.SmallIntegerField(verbose_name='Bitiş')),
                ('ilmihal_ilk', models.SmallIntegerField(verbose_name='Başlangıç')),
                ('ilmihal_son', models.SmallIntegerField(verbose_name='Bitiş')),
                ('yasin', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('mulk', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('nebe', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('igra', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('beyyine', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('duha_alti', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('fil_alti', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('tecvid', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('siyer', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('p_arapca', models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ilmihal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa', models.SmallIntegerField()),
                ('soru', models.TextField(max_length=600)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanicilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('yasin', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('mulk', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('nebe', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('igra', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('beyyine', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('duha_alti', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('fil_alti', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('tecvid', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('siyer', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('p_arapca', models.CharField(blank=True, choices=[('var', 'Var'), ('yok', 'Yok')], default='var', max_length=25, null=True)),
                ('kk_sayfa_ilk', models.SmallIntegerField(verbose_name='Başlangıç')),
                ('kk_sayfa_son', models.SmallIntegerField(verbose_name='Bitiş')),
                ('ilmihal_ilk', models.SmallIntegerField(verbose_name='Başlangıç')),
                ('ilmihal_son', models.SmallIntegerField(verbose_name='Bitiş')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KURANIKERIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure_isim', models.CharField(max_length=100)),
                ('sayfa', models.SmallIntegerField()),
                ('ayet_no', models.SmallIntegerField()),
                ('ayet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PratikArapca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(max_length=600)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='siyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(max_length=600)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tecvid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.TextField(max_length=600)),
                ('aciklama', models.CharField(blank=True, max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='s_tecvid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
                ('tecvid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.tecvid')),
            ],
        ),
        migrations.CreateModel(
            name='s_siyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
                ('siyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.siyer')),
            ],
        ),
        migrations.CreateModel(
            name='s_parapca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
                ('parapca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.pratikarapca')),
            ],
        ),
        migrations.CreateModel(
            name='s_ilmihal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ilmihal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.ilmihal')),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
            ],
        ),
        migrations.CreateModel(
            name='s_ezber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ezber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kuranikerim')),
                ('kullanici_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='randomapp.kullanicilar')),
            ],
        ),
    ]
